name: Feature Implementation
description: Template for implementing new features or improvements
title: "[FEATURE]: "
labels: ["enhancement"]
projects: ["VitalCard/7"]
body:
  - type: input
    attributes:
      label: Description
      description: A detailed description of the feature to be implemented. Include any specific details about functionality, behavior, and the user experience.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Objectives
      description: A clear list of what this feature aims to achieve. These should be key outcomes that are expected once the feature is implemented.
      value: |
        - Objective 1
        - Objective 2
        - Objective 3
        - ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Strategy/Requirements
      description: Detailed requirements and strategy for the implementation of this feature.
      placeholder: |
        - Step-by-step implementation details
        - UX/UI designs and flowcharts
        - Performance targets
        - Security protocols to be followed
        - Dependency management
    validations:
      required: false
  - type: textarea
    attributes:
      label: Tasks
      description: Specific tasks required to implement the feature. Include as many tasks as necessary by breaking down the feature into smaller, manageable units of work.
      value: |
        - [ ] Task 1: Implement X functionality
        - [ ] Task 2: Design Y interface component
        - [ ] Task 3: Test integration with Z service
        - ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Defined criteria that must be met for the feature to be considered complete. These are conditions that the final product must satisfy to be accepted by the product owner or stakeholders.
      value: |
        - Acceptance Criterion 1: Feature performs as expected on all specified platforms
        - Acceptance Criterion 2: All user paths have been tested and pass
        - Acceptance Criterion 3: Feature meets performance benchmarks
        - ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Future Considerations
      description: Any aspects of the feature that are out of scope for the current phase but may need to be considered in future developments.
      placeholder: Note any dependencies on other projects, features, or updates.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Any additional information that might help the developers. This can include links to related issues, feature requests, or external documents.
      value: n/a
    validations:
      required: false
  - type: textarea
    attributes:
      label: Resources
      description: Links to any external resources like mockups, diagrams, documentation, or API references that will be useful for this feature's implementation.
      value: n/a
    validations:
      required: false
