name: Documentation
description: Prepare documentation for the feature/system/data flow/process/etc
title: "[Docs]: Prepare documentation for <feature/component/process>"
labels: ["documentation", "tech-debt"]
type: task
projects: ["VitalCard/7"]
body:
  - type: textarea
    attributes:
      label: Requirements/Tasks
      description: What needs to be documented/described
      value: |
        - [ ] Prepare data flow diagram and publish it to the Gihub repo
        - [ ] Update <ABC> Wiki page with <XYZ> details, etc
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected outcome
      description: What/where should be published once the documents are ready
      value: |
        - Links to the Wiki/Github repo/Sharepoint/etc
    validations:
      required: false
  - type: textarea
    attributes:
      label: Notes
      description: Any extra notes for context
      value: n/a
    validations:
      required: false
