name: DevOps Request
description: Create DevOps / Infrastructure request
title: "[DevOps]: "
labels: ["devops"]
projects: ["VitalCard/7"]
assignees:
  - pranavvitalcard
body:
  - type: textarea
    attributes:
      label: What needs to be done
      description: Provide the list of the tasks that need to be done
      value: |
        1. Setup XYZ
        2. Provide documentation for ABC
        3. etc
    validations:
      required: false
  - type: textarea
    attributes:
      label: Why we need this?
      description: Provide the reason of this request
      value: e.g. Reduce the cost of the infrastructure
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected output
      description: What should be the output of the request
      value: |
        1. Summary of the resources which were updated/removed
        2. Document shared at Sharepoint
        3. etc
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Environment
      description: What environment is in question?
      options:
        - Staging
        - Production
        - Both
        - Not Environment Specific
      default: 0
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the request
      value: n/a
    validations:
      required: false
